/* Generated by Yosys 0.47 (git sha1 647d61dd9, clang++ 16.0.0 -fPIC -O3) */

(* hdlname = "rom" *)
(* src = "./test.v:1.1-32.10" *)
module rom(addr, data);
  (* src = "./test.v:2.22-2.26" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "./test.v:3.22-3.26" *)
  output [7:0] data;
  wire [7:0] data;
  assign data = { addr, addr };
endmodule
